/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Akshat (https://sketchfab.com/shooter24994)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tesseract-cube-43c205c3ea964d96b0e40319c2db5a14
Title: Tesseract Cube
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import * as THREE from 'three';

type CubeModelProps = {
  onHover: (isHovered: boolean) => void;
  position: [number, number, number];
} & React.ComponentProps<'group'>;

export function CubeModel({ onHover, position, ...props }: CubeModelProps) {
  const { nodes, materials } = useGLTF('/tesseract_cube.glb');
  const textRef = useRef<THREE.Mesh | null>(null);
  const cubeRef = useRef<THREE.Group | null>(null);

  // Animation for the cube when hovered
  useFrame((state, delta) => {
    if (cubeRef.current) {
      cubeRef.current.rotation.y += delta * 0.5;

      // Optional animation for text
      if (textRef.current) {
        textRef.current.position.y =
          Math.sin(state.clock.elapsedTime * 2) * 0.1 + 2;
      }
    }
  });

  return (
    <group
      {...props}
      dispose={null}
      scale={0.5}
      position={position}
      onPointerOver={() => onHover(true)}
      onPointerOut={() => onHover(false)}
    >
      <group ref={cubeRef}>
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.Cube_Material_0 as THREE.Mesh).geometry}
          material={materials.Material}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/tesseract_cube.glb');
