import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { ThemeProvider } from 'next-themes';
import './globals.css';
import './Prosemirror.css';
import ThemeToggleButton from '@/shared/ui/ThemeToggleButton';
import Providers from '@/app/Providers';
import dynamic from 'next/dynamic';

const VisitorLogger = dynamic(() => import('@/shared/ui/VisitorLogger'));

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
          <Providers>
            <VisitorLogger />
            {children}
            <ThemeToggleButton />
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
