/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/category/all': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 카테고리 목록 조회
     * @description 모든 카테고리를 조회합니다.
     */
    get: {
      parameters: {
        query?: {
          /** @description 각 카테고리의 게시글 수 포함 여부 */
          includePostCount?: boolean;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 카테고리 목록 조회 성공 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Category'][];
          };
        };
        /** @description 서버 에러 */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /**
     * 새 카테고리 생성
     * @description 새로운 카테고리를 생성합니다. (관리자 전용)
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @description 카테고리 이름 */
            name: string;
            /** @description 카테고리 설명 */
            description?: string;
          };
        };
      };
      responses: {
        /** @description 카테고리 생성 성공 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Category'];
          };
        };
        /** @description 잘못된 요청 (중복된 이름 등) */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description 권한 없음 */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description 서버 에러 */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/posts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Retrieve all posts */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 게시물 목록 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              id?: number;
              title?: string;
              content?: string;
              /** Format: date-time */
              createdAt?: string;
            }[];
          };
        };
      };
    };
    put?: never;
    /**
     * 게시물 생성
     * @description 새로운 게시물을 생성합니다. 관리자 또는 인증된 사용자만 접근 가능합니다.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @description 게시물 제목 */
            title: string;
            /** @description 게시물 내용 */
            content: string;
            /** @description 카테고리 ID */
            categoryId: number;
            /** @description 태그 ID 배열 (선택사항) */
            tags?: number[];
          };
        };
      };
      responses: {
        /** @description 게시물이 성공적으로 생성됨 */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              id?: number;
              title?: string;
              content?: string;
              authorId?: number;
              categoryId?: number;
              /** Format: date-time */
              createdAt?: string;
              /** Format: date-time */
              updatedAt?: string;
            };
          };
        };
        /** @description 잘못된 요청 */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: string;
            };
          };
        };
        /** @description 인증되지 않은 사용자 */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description 권한 없음 */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description 서버 에러 */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              error?: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Category: {
      /** @description 카테고리 고유 ID */
      id: number;
      /** @description 카테고리 이름 */
      name: string;
      /** @description 카테고리 설명 */
      description?: string | null;
      /**
       * Format: date-time
       * @description 생성 일시
       */
      createdAt?: string;
      _count?: {
        /** @description 해당 카테고리의 게시글 수 */
        posts?: number;
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
